#before using, remove ".example" in this file's naming.

http:
  port: port number

db:
  postgres:
    user: user
    port: 5432
    host: db # or use localhost to use without docker container
    database: your database name
    password: "your pawssword"

jwt:
  ACCESS_SECRET_KEY: youraccesssecretkey
  REFRESH_SECRET_KEY: yourrefreshsecretkey

cloud_storage:
  path: "/your/path/to/storage/"
