#before using, remove ".example" in this file's naming.

http:
  port: 1222

db:
  postgres:
    user: user
    port: 5432
    host: db # or use localhost to use without docker container
    database: your database name
    password: "your passsword"

jwt:
  ACCESS_SECRET_KEY: youraccesssecretkey
  REFRESH_SECRET_KEY: yourrefreshsecretkey

cloud_storage:
  path: "/your/path/to/storage/"

aws:
  region: 111
  access_key_id: 111
  secret_access_key: 111
  bucket_name: 111
